### ISSUE TITLE
Event List

### ISSUE THREAD

**Issue by Equanox** [xmidt-org/codex-deploy#101]
Do you have a good starting point to figure out which events are sent from RDKB devices?

**Comment by kcajmagic** [comment]
@Equanox, right now codex focuses mainly on Online and Offline events which is generated from talaria. We would like to improve this functionality for better tagging of events. (https://github.com/xmidt-org/svalinn/issues/100)

I am unaware of a list of events sent from clients of parodus.

**Comment by kcajmagic** [comment]
Closing issue since event generation is responsible from the clients of parodus.

**Comment by Equanox** [comment]
Thx for clarification.
