### ISSUE TITLE
Add Heimdall to README

### ISSUE THREAD

**Issue by kristinaspring** [xmidt-org/codex-deploy#92]
github.com/xmidt-org/heimdall

**Comment by kristinaspring** [comment]
Heimdall should be listed in the services.  It's a consumer of Codex but also requests directly from the database.  The image can be updated as well.

**Comment by BrittanyIstenes** [comment]
I would like to take this one.  Can you please assign it to me?

**Comment by kristinaspring** [comment]
Partially fixed in https://github.com/xmidt-org/codex-deploy/pull/102

**Comment by BrittanyIstenes** [comment]
Adding the new image 10/23/19

**Comment by kristinaspring** [comment]
Fixed in https://github.com/xmidt-org/codex-deploy/pull/103
