### ISSUE TITLE
Update docker-compose process

### ISSUE THREAD

**Issue by kcajmagic** [xmidt-org/codex-deploy#95]
Update the codex docker-compose process to be like xmidt-org/xmidt#12 implemented here https://github.com/xmidt-org/xmidt/pull/15

**Comment by firfircelik** [comment]
@kcajmagic is this still open?

**Comment by kcajmagic** [comment]
@firfircelik this issue is still open. The main goal of this issue is to simplify the build process for other users so one doesn't have to build all the containers when doing local testing, or playing around with codex.

**Comment by uLan08** [comment]
Hi @firfircelik , are you still looking into this? I'd like to take this on if you don't mind.

**Comment by firfircelik** [comment]
@uLan08 you can take it if you want.

**Comment by uLan08** [comment]
Alright.

**Comment by kcajmagic** [comment]
Fixed in #104
